// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVDsoEKHzuSajQPsAU1ebuRpLD681I87c',
    appId: '1:444892180401:web:32eb49a4e32f4e19661790',
    messagingSenderId: '444892180401',
    projectId: 'chat-sphere-777bc',
    authDomain: 'chat-sphere-777bc.firebaseapp.com',
    storageBucket: 'chat-sphere-777bc.firebasestorage.app',
    measurementId: 'G-1XBL44NV54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWEyNONqYIUXV_cN4V_NzAeY0BZ8hjm10',
    appId: '1:444892180401:android:7ba744e685b2ce47661790',
    messagingSenderId: '444892180401',
    projectId: 'chat-sphere-777bc',
    storageBucket: 'chat-sphere-777bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvkktMHirDptm5YQVHYaNSTtQLgAimiVw',
    appId: '1:444892180401:ios:fdd5061b04420e52661790',
    messagingSenderId: '444892180401',
    projectId: 'chat-sphere-777bc',
    storageBucket: 'chat-sphere-777bc.firebasestorage.app',
    iosBundleId: 'com.example.chatSphereApp',
  );
}
